// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions: 1.4.2-old

import request, { Response } from '@/utils/axiosReq'
import { IEmpty } from './empty.pb'


export enum ESex {
  SexNone = 0,   // 无意义占位用
  SexMale = 1,   // 男性
  SexFemale = 2  // 女性
}

export interface IRequestUsers {
  page: number      // 页码
  page_size: number // 每页数量
}

export interface IUser {
  id?: (number | null)       // 主键ID
  username?: (string | null) // 用户名
  email?: (string | null)    // 邮箱
  sex?: (ESex | null)        // 性别
}

export interface IResponseUsers {
  data_list?: (IUser[] | null) 
}

export interface IRequestNil {
  __placeholder__?: any
}

export interface IResponseNil {
  __placeholder__?: any
}

export interface IRequestPostEmpty {
  name?: (string | null) 
}

export interface ICommonNil {
  __placeholder__?: any
}


// 获取用户列表
export function GetUsers(params: IRequestUsers): Promise<Response<IResponseUsers>> {
  return request({
    url: "/users/v1/",
    method: "GET",
    params,
  })
} 

// 添加用户
export function PostUsers(data: IUser): Promise<Response<IResponseNil>> {
  return request({
    url: "/users/v1/",
    method: "POST",
    data,
  })
} 

/**
 * 获取用户详情
 * @Param { number } id - 
 */
export function GetUserInfo(id: number, params: IRequestNil): Promise<Response<IUser>> {
  return request({
    url: "/users/v1/" + id + "/",
    method: "GET",
    params,
  })
} 

/**
 * 用户下载
 * @Param { number } id - 
 */
export function GetUserInfoDownload(id: number, params: IRequestNil): Promise<Response<IResponseNil>> {
  return request({
    url: "/users/v1/" + id + "/",
    method: "GET",
    params,
  })
} 

// 空参数示例1
export function GetCommonNil(): Promise<Response<IUser>> {
  return request({
    url: "/users/v1/common/nil/",
    method: "GET",
  })
} 

// 空参数示例2
export function PostEmpty(params: IRequestPostEmpty): Promise<Response<IEmpty>> {
  return request({
    url: "/users/v1/empty/",
    method: "GET",
    params,
  })
} 


