// Code generated by protoc-gen-bic. DO NOT EDIT.
// versions:1.2.1

import request from '@/utils/axiosReq'
import { http } from './proto'

/**
 * 获取用户列表
 * @param params - 
 * @returns
 */
export function GetUsers(params: http.IRequestUsers) {
  return request({
    url: "/users/v1/",
    method: "GET",
    params,
  })
} 

/**
 * 添加用户
 * @param data - 
 * @returns
 */
export function PostUsers(data: http.IUser) {
  return request({
    url: "/users/v1/",
    method: "POST",
    data,
  })
} 

/**
 * 获取用户详情
 * @Param id - uint id
 * @param params - 
 * @returns
 */
export function GetUserInfo(id: number, params: http.IRequestNil) {
  return request({
    url: "/users/v1/" + id + "/",
    method: "GET",
    params,
  })
} 

/**
 * 用户下载
 * @Param id - uint id
 * @param params - 
 * @returns
 */
export function GetUserInfoDownload(id: number, params: http.IRequestNil) {
  return request({
    url: "/users/v1/" + id + "/",
    method: "GET",
    responseType: "blob",
    isDownLoadFile: true,
    params,
  })
} 

/**
 * 空参数示例1
 * @returns
 */
export function GetCommonNil() {
  return request({
    url: "/users/v1/common/nil/",
    method: "GET",
  })
} 

/**
 * 空参数示例2
 * @param params - 
 * @returns
 */
export function PostEmpty(params: http.IRequestPostEmpty) {
  return request({
    url: "/users/v1/empty/",
    method: "GET",
    params,
  })
} 


